version: '3.5'

services:
  shopee:
    container_name: shopee
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src:rw
    env_file: env/dev.env
    networks:
      - shopee-network
    ports:
      - 5600:5000
    tty: true
    command: cron -f

  shopee_phpmyadmin:
    container_name: shopee_phpmyadmin
    image: phpmyadmin/phpmyadmin:4.9.4
    networks:
      - shopee-network
    environment:
      - PMA_HOST=shopee_mysql
    ports:
      - 8073:80

  shopee_mysql:
    container_name: shopee_mysql
    image: mysql:5.6
    networks:
      - shopee-network
    environment:
      - TZ=Asia/Taipei
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/mysql/mysql_data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf


networks:
  shopee-network:
    name: shopee
    driver: bridge
